// Static fallback data, shown only when the live SportsGameOdds feed is
// unreachable. Same shape as odds.js#buildLiveItems, but fabricated.

export const SAMPLE_ITEMS = [
  {
    id: 'sample-1',
    league: 'NFL',
    marketType: 'Moneyline',
    matchup: 'Sample Falcons @ Sample Wolves',
    startsAt: null,
    name: 'Sample Falcons @ Sample Wolves — Moneyline (Sample Wolves)',
    bookmakers: [
      { book: 'sample_a', label: 'Sample Book A', american: '-105', decimal: 1.95, deeplink: null },
      { book: 'sample_b', label: 'Sample Book B', american: '-112', decimal: 1.89, deeplink: null },
      { book: 'sample_c', label: 'Sample Book C', american: '-108', decimal: 1.93, deeplink: null },
    ],
    bestPrice: '-105',
    bestVendor: 'Sample Book A',
    bestDeeplink: null,
    fairOdds: '-110',
    openBookOdds: '-108',
    edgePct: 2.6,
    isOutlier: true,
  },
  {
    id: 'sample-2',
    league: 'NFL',
    marketType: 'Spread',
    matchup: 'Sample Falcons @ Sample Wolves',
    startsAt: null,
    name: 'Sample Falcons @ Sample Wolves — Spread (Sample Falcons)',
    bookmakers: [
      { book: 'sample_a', label: 'Sample Book A', american: '-108', decimal: 1.93, deeplink: null },
      { book: 'sample_b', label: 'Sample Book B', american: '-115', decimal: 1.87, deeplink: null },
    ],
    bestPrice: '-108',
    bestVendor: 'Sample Book A',
    bestDeeplink: null,
    fairOdds: '-110',
    openBookOdds: '-110',
    edgePct: 1.0,
    isOutlier: false,
  },
  {
    id: 'sample-3',
    league: 'NBA',
    marketType: 'Total',
    matchup: 'Sample Comets @ Sample Rays',
    startsAt: null,
    name: 'Sample Comets @ Sample Rays — Total Over 224.5',
    bookmakers: [
      { book: 'sample_a', label: 'Sample Book A', american: '+102', decimal: 2.02, deeplink: null },
      { book: 'sample_b', label: 'Sample Book B', american: '-105', decimal: 1.95, deeplink: null },
      { book: 'sample_c', label: 'Sample Book C', american: '-102', decimal: 1.98, deeplink: null },
    ],
    bestPrice: '+102',
    bestVendor: 'Sample Book A',
    bestDeeplink: null,
    fairOdds: '-105',
    openBookOdds: '-108',
    edgePct: 3.5,
    isOutlier: true,
  },
];
